// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhhidklgpblfgebqfyjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaGlka2xncGJsZmdlYnFmeWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzgzMjQsImV4cCI6MjA3MzI1NDMyNH0.BfwHgWOX-dacqCy8aMvqYdSDhbQSquyW8SJ6I9ilBho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});